source "https://rubygems.org"

gem "sinatra", :require => "sinatra/base"
gem "sinatra-contrib"

gem "httparty"
gem "shotgun"
gem "pry"
gem "sinatra-activerecord"
gem "rake"
gem "mysql2"
gem "composite_primary_keys", "=9.0.0"
gem "sass"
gem "haml"
gem "sprockets"
gem "uglifier"
